default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>

development:
  <<: *default
  database: time_log_development

test:
  <<: *default
  database: time_log_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
